### ISSUE TITLE
samtools view doesn't accept region arguments

### ISSUE THREAD

**Issue by drtconway** [PMCC-BioinformaticsCore/janis-bioinformatics#30]
Hi Janis,

I have a use-case where I use a samtools invocation like the following:

```
samtools view -b my-bam.bam 20 | ....
```

Which extracts the alignments mapping to chromosome 20.

As far as I can see, this is not currently supported in the SamToolsView binding, even though it is implied by the included samtools documentation.

**Comment by illusional** [comment]
You're right @drtconway, looks like I didn't capture the interface of the tool correctly. I'm not as familiar with using the region argument, would being a Array(String) suffice here (as seen in the linked issue). 

If you're happy, I'll merge the linked PR.

**Comment by drtconway** [comment]
Perfect.
