### ISSUE TITLE
SamToolsSort outputs

### ISSUE THREAD

**Issue by drtconway** [PMCC-BioinformaticsCore/janis-bioinformatics#32]
Hi Janis.

Is there a reason SamToolsSort is trying to return the temporary files (which samtools sort removes) as outputs? That seems bogus to me.

The argument relating to it simply lets you control the names of the files, not because they're outputs, but to avoid name collisions.

Having it as an output makes it's use more complicated than necessary because you have to name the output.

**Comment by illusional** [comment]
When I built the tool wrapper, my intention was:

> you can specify a prefix, so you might want to specify an output

The output is marked as optional, though the glob is wrong. I've issued a PR to comment out this line.
