### ISSUE TITLE
Output BAM doesn't get copied.

### ISSUE THREAD

**Issue by drtconway** [PMCC-BioinformaticsCore/janis-bioinformatics#34]
Hi Janis,

I made a derived class of BioinformaticsTool  and had the following definition for outputs:
```python
        return [ToolOutput("out", Bam, glob=WildcardSelector("*.bam"))]
```
but no file was copied. I see from the execution directory, the BAM is there, and the glob- file has captured it, but it has not been copied to the output directory.

Is BAM not a subclass of File?

**Comment by illusional** [comment]
Hey @drtconway, sorry for the late reply. `Bam` is a subclass of file, and this should work as you'd expect, this sounds like it might be a problem with the janis-assistant. Could you provide a contained example where this isn't working and I can investigate.

Maybe through email might be easiest, though feel free to put the tool here too.

**Comment by drtconway** [comment]
I attempted to reproduce the problem and failed.

I think it may have been spurious. The outputs don't necessarily get copied immediately after the step finishes, since it requires the parent to wake up and copy the outputs. It may have been that when I looked they hadn't been copied yet.

I'll close this issue, and if it comes up again, file a full repro in the first place.

T.
