### ISSUE TITLE
SamtoolsFaidx missing

### ISSUE THREAD

**Issue by drtconway** [PMCC-BioinformaticsCore/janis-bioinformatics#42]
Janis requires fasta indexes to be present, but does not provide a way of making them.

**Comment by illusional** [comment]
Hey @drtconway, it is in the repository, but called `SamtoolsIndex`: https://janis.readthedocs.io/en/latest/tools/bioinformatics/samtools/samtoolsindex.html ([Github](https://github.com/PMCC-BioinformaticsCore/janis-bioinformatics/blob/master/janis_bioinformatics/tools/samtools/faidx/base.py))

There's also a little pipeline to index a fasta file (but it currently doesn't output to a single FastaWithIndexes object).
